pipeline{
    agent any
    environment {
        PATH = "$PATH:C:\maven\apache-maven-3.8.4\bin"
    }
    stages{
       stage('GetCode'){
            steps{
                git ''
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
        stage('SonarQube analysis') {
//    def scannerHome = tool 'SonarScanner 4.6';
        steps{
        withSonarQubeEnv('sonarqube-9.3') { 
        // If you have configured more than one global server connection, you can specify its name
//      sh "${scannerHome}/bin/sonar-scanner"
        sh "mvn sonar:sonar"
    }
        }
        }
       
    }
}
